### ISSUE TITLE
Unable to show lightdm-deepin-greeter when the userid is too big

### ISSUE THREAD

**Issue by shenjiangqiu** [linuxdeepin/lightdm#1]
When my user id is 1000, the lightdm can successfully start greeter, but I change my user id to 133376, when boot, the screen just shows whole white without any materials.

**Comment by cheese** [comment]
lightdm-deepin-greeter is provided in project https://github.com/linuxdeepin/dde-session-ui

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
